services:
  frontend:
    build: ./frontend/position-book-system/
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/position-book-system:/app
    environment:
      NODE_ENV: development
    env_file:
      - ./frontend/position-book-system/.env
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm cache clean --force && npm run dev"

  backend:
    build: ./backend/position-book-system/
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - kafka-topics-generator  # Wait for topics to be created
    environment:
      # Add Kafka configuration for your backend
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - back-tier
      - kafka-tier

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-tier
      - back-tier

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - kafka-tier
      - back-tier

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-topics-generator
    depends_on:
      - kafka
    command: >
      bash -c
        "sleep 10s &&
        kafka-topics --create --topic=api-logs --if-not-exists --bootstrap-server=kafka:29092 --partitions=1 --replication-factor=1"
    networks:
      - kafka-tier

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  # The presence of these objects is sufficient to define them
  kafka-tier: {}
  front-tier: {}
  back-tier: {}
